# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f41800a8125ed6ff64816d487b1af82390c7e289d913a15902a4296ee7e60cfffee6fec0e58a429b584bdb660e8af5ff16e983f27e8ad2189ca72d89516619f9

test:
  secret_key_base: b476c6e5687a9cc672f400718aaeff2530fe8b25dae398eb33ce6a1e81142f27622d30936d26bfe69c0148138020a001fba7f524609dc494df65af675c60cf41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
